name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      TEST_IF_WORKS_ENV_VAR: ${{ secrets.TEST_IF_WORKS_ENV_VAR }}
      REDIRECT_URI: "https://speechmatics-selfserve-test.znn.app/getting-started/"
      POST_LOGOUT_REDIRECT_URI: "https://speechmatics-selfserve-test.znn.app/login/"
      SIGNUP_SIGNIN_POLICY: "B2C_1_susi"
      RESET_PASS_POLICY: "B2C_1_reset"
      EDIT_PROFILE_POLICY: "B2C_1_edit_profile"
      AUTHORITY_DOMAIN: "testb2cmichalp.b2clogin.com"
      POLICY_DOMAIN: "testb2cmichalp.onmicrosoft.com"
      AUTH_CLIEND_ID: "cc0ee2fd-cf10-4d64-b87c-727e1a130502"
      TEST_API_CALL_ENDPOINT: "https://testapp-mipo.azurewebsites.net/hello"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_COAST_01B5E7B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "out" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_COAST_01B5E7B03 }}
          action: "close"
