name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - general_dev_mars
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - general_dev_mars

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      REDIRECT_URI: 'https://dev-mars-portal.ui-internal.speechmatics.com/login/'
      POST_LOGOUT_REDIRECT_URI: 'https://dev-mars-portal.ui-internal.speechmatics.com/login/'
      REDIRECT_URI_INVITATION: 'https://dev-mars-portal.ui-internal.speechmatics.com/signup/'
      ENDPOINT_API_URL: 'https://staging-mp.speechmatics.com/v1'
      RUNTIME_API_URL: 'https://selfservice-asr.api.speechmatics.com/v2'
      CHARGIFY_PUBLIC_KEY: 'chjs_dv9b2hv745b3dc5knfkddy64'
      CHARGIFY_SERVER_HOST: 'https://speechmatics-staging.chargify.com'
      SIGNIN_POLICY: 'https://identity.speechmatics.com/identity.speechmatics.com/B2C_1A_SIGNIN_ONLY'
      INVITATION_SIGNUP_POLICY: 'https://identity.speechmatics.com/identity.speechmatics.com/B2C_1A_SIGNUP_INVITATION'
      RESET_PASSWORD_POLICY: 'https://identity.speechmatics.com/identity.speechmatics.com/B2C_1A_PASSWORDRESET'
      AUTHORITY_DOMAIN: 'identity.speechmatics.com'
      POLICY_DOMAIN: 'identity.speechmatics.com'
      AUTH_CLIENT_ID: '21d50769-1b5b-414d-be58-cc27ea9dc1fa'
      DEFAULT_B2C_SCOPE: 'https://identity.speechmatics.com/21d50769-1b5b-414d-be58-cc27ea9dc1fa/User.Read'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up node and test
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci && npm test

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_SEA_0CA2C8E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: 'out' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_SEA_0CA2C8E03 }}
          action: 'close'
