name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - general_ui_test
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - general_ui_test

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      REDIRECT_URI: 'https://test-portal.ui-internal.speechmatics.com/'
      SIGNIN_POLICY: 'https://speechmaticsb2cReg.b2clogin.com/speechmaticsb2cReg.onmicrosoft.com/B2C_1_susi'
      POST_LOGOUT_REDIRECT_URI: 'https://test-portal.ui-internal.speechmatics.com/'
      RESET_PASSWORD_POLICY: 'https://speechmaticsb2cReg.b2clogin.com/speechmaticsb2cReg.onmicrosoft.com/B2C_1_reset_password'
      AUTHORITY_DOMAIN: 'speechmaticsb2cReg.b2clogin.com'
      POLICY_DOMAIN: 'speechmaticsb2cReg.onmicrosoft.com'
      AUTH_CLIENT_ID: 'ae7e7ece-43f4-41bc-a20a-98422de9f540'
      ENDPOINT_API_URL: 'https://staging-qa-mp.speechmatics.com/v1'
      RUNTIME_API_URL: 'https://selfservice-qa-asr.api.speechmatics.com/v2'
      DEFAULT_B2C_SCOPE: 'https://speechmaticsb2cReg.onmicrosoft.com/ae7e7ece-43f4-41bc-a20a-98422de9f540/User.Read'
      CHARGIFY_PUBLIC_KEY: 'chjs_txcb7j9x3pck49n7zr2kz7ns'
      CHARGIFY_SERVER_HOST: 'https://speechmatics-qa.chargify.com'
      CALENDLY_GENERAL_FORM_URL: 'https://calendly.com/speechmatics/book-a-meeting-with-speechmatics-saas-portal?salesforce_uuid=1331'
      CALENDLY_REALTIME_FORM_URL: 'https://calendly.com/speechmatics/book-a-meeting-with-speechmatics-real-time-saas?salesforce_uuid=1332'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_ISLAND_0A73D9810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "out" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_ISLAND_0A73D9810 }}
          action: "close"
          
          
