name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - general_dev_jupiter
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - general_dev_jupiter

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      REDIRECT_URI: 'https://dev-jupiter-portal.ui-internal.speechmatics.com/login/'
      POST_LOGOUT_REDIRECT_URI: 'https://dev-jupiter-portal.ui-internal.speechmatics.com/login/'
      REDIRECT_URI_INVITATION: 'https://dev-jupiter-portal.ui-internal.speechmatics.com/signup/'
      SIGNIN_POLICY: 'https://speechmaticsb2cReg.b2clogin.com/speechmaticsb2cReg.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN'
      #INVITATION_SIGNUP_POLICY: 'https://speechmaticsb2cReg.b2clogin.com/speechmaticsb2c.onmicrosoft.com/B2C_1A_SIGNUP_INVITATION'
      RESET_PASSWORD_POLICY: 'https://speechmaticsb2cReg.b2clogin.com/speechmaticsb2cReg.onmicrosoft.com/B2C_1A_PASSWORDRESET'
      AUTHORITY_DOMAIN: 'speechmaticsb2cReg.b2clogin.com'
      POLICY_DOMAIN: 'speechmaticsb2cReg.onmicrosoft.com'
      AUTH_CLIENT_ID: '4031731a-7a16-47e3-919e-fbc2a35d9af3'
      ENDPOINT_API_URL: 'https://sm-mp-dev-ingress-b.westeurope.cloudapp.azure.com/v1'
      RUNTIME_API_URL: 'https://speechmatics-dev-ingress-b.westeurope.cloudapp.azure.com/v2'
      DEFAULT_B2C_SCOPE: 'https://speechmaticsb2cReg.onmicrosoft.com/IdentityExperienceFramework/user_impersonation'
      CHARGIFY_PUBLIC_KEY: 'chjs_6nnmqcxmp4nrbnmf2spmwm63'
      CHARGIFY_SERVER_HOST: 'https://speechmatics-dev.chargify.com'
      REALTIME_URL: 'wss://transcribe.selfservice-dev-rt-eu-a.rt.speechmatics.com/v2'
      CALENDLY_GENERAL_FORM_URL: 'https://calendly.com/speechmatics/book-a-meeting-with-speechmatics-saas-portal?salesforce_uuid=1331'
      CALENDLY_REALTIME_FORM_URL: 'https://calendly.com/speechmatics/book-a-meeting-with-speechmatics-real-time-saas?salesforce_uuid=1332'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_COAST_02348BE03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "out" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_COAST_02348BE03 }}
          action: "close"
